version: 0.2
 
phases:
  pre_build:
    commands:
      - echo prebuild phase
      - echo $CODEBUILD_INITIATOR
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo $COMMIT_HASH
      - |
        if echo $CODEBUILD_INITIATOR | grep -qe "-development$"; then
          ENV_TYPE=development;
          CLOUDFRONT_ID="E6UGVOB6YIWQG";
          S3_BUCKET=reblie-admin-portal-dev;
        fi;
      - |
        if echo $CODEBUILD_INITIATOR | grep -qe "-staging$"; then
          ENV_TYPE=staging;
          CLOUDFRONT_ID="";
          S3_BUCKET=;
        fi;
      - |
        if echo $CODEBUILD_INITIATOR | grep -qe "-production$"; then
          ENV_TYPE=production;
          CLOUDFRONT_ID="";
          S3_BUCKET=;
        fi;
      - echo $ENV_TYPE
      - payload=$(echo -n '{"application":"development", "repoName":"reblie-admin-portal"}' | base64)
      - aws lambda invoke --function-name reblie-web-read-env --invocation-type RequestResponse --region us-east-1 --payload "$payload" app_env.json
      - cat app_env.json | jq -r '.body' >> .env
      - cat .env
      - sed -i 's|"homepage"[^,$]*|"homepage":"$COMMIT_HASH"|g' ./package.json
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying to S3 ${S3_BUCKET}...
      - aws s3 sync ./build/ s3://${S3_BUCKET}/$COMMIT_HASH
      - aws s3 cp ./build/index.html s3://${S3_BUCKET}/